[profile.default]
script = 'script'
test = 'test'
build_info = true
extra_output = ['storageLayout']
fs_permissions = [{ access = "read-write", path = "./"}]
allow_paths = ["../.."]
remappings=[
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/',
  '@sphinx-labs/plugins/=node_modules/@sphinx-labs/plugins/contracts/foundry/',
  '@sphinx-labs/contracts/=node_modules/@sphinx-labs/contracts/',
  'sphinx-forge-std/=node_modules/sphinx-forge-std/src/',
  'sphinx-solmate/=node_modules/sphinx-solmate/src/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
gnosis_chiado = "${GNOSIS_CHIADO_RPC_URL}"
polygon_zkevm_goerli = "${POLYGON_ZKEVM_TESTNET_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnb_testnet = "${BNB_TESTNET_RPC_URL}"
linea_goerli = "${LINEA_GOERLI_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"
fantom_testnet = "${FANTOM_TESTNET_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
